### ISSUE TITLE
In the Java class, index should be casted as long

### ISSUE THREAD

**Issue by mufumbo** [delight-im/ShortURL#1]
You will need to replace this: 
final long idx = num % BASE;

Otherwise it explodes for long longs.

**Comment by ocram** [comment]
Thanks!

Are you referring to this line?
https://github.com/delight-im/ShortURL/blob/ef1d544a075830df5cff5d0429c5b4bc7b9ff5a0/Java/ShortURL.java#L25

Well, could you explain why you think this change is necessary?
- `num` is `int`
- `BASE` is `int`
- `num % BASE` should always be between `0` and `BASE - 1`

**Comment by mufumbo** [comment]
Oh, that's correct. 

I didn't noticed that in my code I had changed to long.
