### ISSUE TITLE
what if path starts with "2"

### ISSUE THREAD

**Issue by sandeepkalra** [delight-im/ShortURL#33]
I was testing my Go version of the code and just found that if the path in Decode(s string) starts with 2, the index converts to 0, and the result is that the string cannot be reversed to the original. I have added test cases to benchmark and test. Please have a look:

https://github.com/sandeepkalra/ShortURL/blob/master/Go/shortUrl.go

Am I missing something?

**Comment by sandeepkalra** [comment]
This is the link for test: https://github.com/sandeepkalra/ShortURL/blob/master/Go/shortUrl_test.go

I think all implementations of Decode across all languages (C++, C#, PHP) etc have the ID (conversion of the path to number) start with 0.

**Comment by sandeepkalra** [comment]
I have fixed the problem in "Go" version by changing the algorithm a little bit. Please see the pull-request.

**Comment by ocram** [comment]
Thanks!

What was the actual problem you were trying to fix? And how did you fix it exactly?

With our base-51 system (which uses the specified alphabet), the character `2` is the very first entry, i.e. it’s our zero. Just as with the character `0` in the common base-10 system, a leading zero can be dropped without changing the number represented with the specific sequence of characters.

So the sequence `2BCDFGHJP` in our base-51 is actually equivalent to `BCDFGHJP` and the encoding will only ever produce that simpler form `BCDFGHJP`.

Hope that helps!

**Comment by sandeepkalra** [comment]
Well, If that is by design, then I am fine with it, and I will revert the
changes I made in Go Code.

Best Regards,
Sandeep Kalra
