### ISSUE TITLE
Please look at my Gist for a way to enhance your ShortURL

### ISSUE THREAD

**Issue by firepacket** [delight-im/ShortURL#41]
*Better privacy
*Better capacity
*Shorter URLs with longer numbers
*Support for long datatype

https://gist.github.com/firepacket/00f6a64acfa61365d56e79cd5c564095

**Comment by ocram** [comment]
Thanks!

The chosen alphabet is obviously a known tradeoff, and we’re happy with its current value, which has good properties and compatibility.

**Comment by firepacket** [comment]
Actually I realized this method supports the ulong, the largest datatype in c#, which I imagine would be useful for larger companies. Take another look, I also fixed a few bugs:

https://gist.github.com/firepacket/8e9077792ea63a069ca6b0acf3dd4d21

And what are your specific issues with compatibility?
