### ISSUE TITLE
in 64bit php, everything between 0x7ffffffffffffE00 - PHP_INT_MAX is returned as float

### ISSUE THREAD

**Issue by divinity76** [delight-im/ShortURL#8]
the following code should echo `FOUND after 1 attempt(s)` , 
and it works as expected in 32bit php, but in 64bit php it echos `FOUND after 513 attempt(s)`

``` <?php
for($i = PHP_INT_MAX; $i > 0; -- $i) {
    if (! is_float ( ShortURL::decode ( ShortURL::encode ( $i ) ) )) {
        //var_dump ( $i );
        die ( 'FOUND after '.((PHP_INT_MAX-$i)+1).' attempt(s)' );
    }
}
die ( 'NOT FOUND' );
```

**Comment by ocram** [comment]
Thanks for your effort here!

We should definitely do something to find out the limit, as I said in https://github.com/delight-im/ShortURL/issues/7, but I think what you did is the wrong direction, isn't it? You found the _largest_ number, other than `PHP_INT_MAX` in 64-bit PHP, that doesn't work. But what we need is actually the _smallest_ such number, which requires much more computing power or time.

**Comment by divinity76** [comment]
Actually, i cannot guarantee that it's the lowest failing number, but i can guarantee that it's not the highest failing number. for instance, all the following numbers (which are all higher) also fails:
```

**Comment by divinity76** [comment]
actually, it's neither. the highest failing number is `9223372036854775806`

but i don't know what the lowest failing number is. other than that it is <=`9223372036854773283`
