### ISSUE TITLE
in 64bit php, everything >= 0xE33BF7209CBFD54 is decoded (or encoded?) incorrectly

### ISSUE THREAD

**Issue by divinity76** [delight-im/ShortURL#9]
in 64bit php, the following code

```
<?php 
define ( "NUM", 1023372036854775122 );
for($i = NUM; $i < PHP_INT_MAX; ++ $i) {
    $encoded = ShortURL::encode ( $i );
    $decoded = ShortURL::decode ( $encoded );
    if ($i !== $decoded) {
        var_dump ( $i, $encoded, $decoded );
        die ( 'FAILED after ' . (($i - NUM) + 1) . ' attempt(s)' . PHP_EOL );
    }
}
die ( 'SUCCESS' );
```

should echo SUCCESS (but due to #8 , we know it would fail at 9223372036854775296, but it's much worse than that) , in 64bit php, it echoes

```
int(1023372036854775124)
string(11) "bDt2WgSwgz3"
int(1023372036854775073)
FAILED after 3 attempt(s)
```

somehow 1023372036854775124 turned into 1023372036854775073

**Comment by ocram** [comment]
Thanks a lot!

The starting point `1023372036854775122` has been arbitrarily chosen here, right? Your code is exactly what we need to test this, except that the starting point has to be `0` or `2,147,483,647` instead -- which unfortunately requires too much time to compute, I guess.

Please see my comments in https://github.com/delight-im/ShortURL/issues/7 and https://github.com/delight-im/ShortURL/issues/8 as well.
